---
- name: install dependencies | Debian
  package:
    pkg: "{{ item }}"
    update_cache: true
    cache_valid_time: 86400
    state: present
  with_items:
    - gcc
    - make
    - libssl-dev
    - libsqlite3-dev
    - libbz2-dev
    - libffi-dev
    - python3-pip
  when: ansible_os_family == "Debian"
  become: true

- name: install dependencies | RedHat
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make
    - openssl-devel
    - sqlite-devel
    - bzip2-devel
    - libffi-devel
  when: ansible_os_family == "RedHat"
  become: true

- name: install openssl 1.1 | RedHat
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openssl11-devel
  when: 
    - ansible_os_family == "RedHat"
    - python_version is version('3.10', '>=')
  become: true

- name: Install GnuPG
  package:
    name: gnupg
    state: present
  when: python_verify_gpg_signature|bool
  become: true
