---
- name: Install Python3 Dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution'] != "RedHat"

# Install python from package
- name: Install Python3 packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ python3_packages }}"
