---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - set_fact:
        python_install_from_source: true
        python_version: "{{ lookup('env', 'PYTHON_VERSION') }}"

    - name: Install dependencies from CentOS Repositories | RHEL 7+
      when:
       - ansible_distribution == "RedHat"
       - ansible_distribution_major_version == "7"
      block:

      - set_fact:
          _tmp_repos:
            - name: base
              url: http://mirror.centos.org/centos/7/os/x86_64/
            - name: sclo
              url: http://mirror.centos.org/centos/7/sclo/x86_64/rh/

          _tmp_packages:
            - name: bzip2-devel
              repo: base
            - name: devtoolset-11
              repo: sclo, base

      - name: Add Temporary Repositories | RHEL
        yum_repository:
            name: "{{ item.name }}"
            description: "Centos {{ ansible_distribution_major_version }} - {{ item.name }}"
            baseurl: "{{ item.url }}"
            enabled: false
        with_items: "{{ _tmp_repos }}"
        loop_control:
          label: "{{ item.name }}"

      - name: Install missing packages | RHEL
        yum:
          name: "{{ item.name }}"
          state: present
          enablerepo: "{{ item.repo }}"
          disable_gpg_check: true
        with_items: "{{ _tmp_packages }}"
        loop_control:
          label: "{{ item.name }}"



    - name: Install prerequisites
      block:
        - name: Update apt cache
          apt:
            update_cache: true
            cache_valid_time: 600
          changed_when: false
          when: ansible_os_family == "Debian"

  roles:
    - role: ansible-python
      tags:
        - python
