---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Define variables.
      set_fact:
        python_install_from_source: true
        python_version: "{{ lookup('env', 'PYTHON_VERSION') }}"

    # in RHEL7, devtoolset-11 is available via `rhel-7-seerver-rhscl`,
    # since we are installing packages from CentOS repositories,
    # we have to install centos-release-scl
    - name: Install dependencies | RHEL 7+
      yum:
        name: centos-release-scl
        state: present
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == "7"

    - name: Install prerequisites
      block:
        - name: Update apt cache
          apt:
            update_cache: true
            cache_valid_time: 600
          changed_when: false
          when: ansible_os_family == "Debian"

  roles:
    - role: ansible-python
      tags:
        - python
