---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  env:
    PYTHON_VERSION: ${MOLECULE_PYTHON_VERSION:-3.8.16}
    PYTHON_INSTALL_FROM_SOURCE: ${MOLECULE_PYTHON_INSTALL_FROM_SOURCE:-false}
verifier:
  name: testinfra
  options:
    s: true
    verbose: true
